/**
 * First is the first bottom left (black)
 */
export const Periods = {
    fr:
        [
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì : Solstice d’hiver',
                '蚯蚓結 – qiūyǐn jié : Les vers de terre se replient sur eux-mêmes.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì : Solstice d’hiver',
                '麋角解 – mí jiǎo jiě : Le cerf se débarrasse de ses bois.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì : Solstice d’hiver',
                '水泉動 – shuǐquán dòng : Les eaux et les sources dégèlent.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán : Petit froid',
                '雁北鄉 – yàn běi xiāng : Les oies sauvages partent vers le nord.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán : Petit froid',
                '鵲始巢 – què shǐ cháo : La pie fait son nid.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán : Petit froid',
                '野鶏始雛 – yě jī shǐ chú : Le faisan commence à crier.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán : Grand froid',
                '鶏始乳 – jī shǐ rǔ : Les poules commencent à couver.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán : Grand froid',
                '鷙鳥厲疾 – zhì niǎo lì jí : Les rapaces sont rapides et terribles.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán : Grand froid',
                '水澤腹堅 – shuǐ zé fù jiān : Les eaux et les lacs se couvrent d’une épaisse couche de glace.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn : Établissement du printemps',
                '東風解凍 – dōngfēng jiědòng : Le vent d’est fait fondre la gelée.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn : Établissement du printemps',
                '蟄蟲始振 – zhéchóng shǐzhèn : Les insectes hibernants commencent à se réveiller.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn : Établissement du printemps',
                '魚上冰 – yú shàng bīng : Les poissons remontent les glaces.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ : Eau de pluie',
                '獺祭魚 – tǎ jì yú : La loutre offre du poisson en sacrifice.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ : Eau de pluie',
                '鴻雁來 – hóngyàn lái : Les oies sauvages arrivent.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ : Eau de pluie',
                '草木萌動 – cǎomù méngdòng : Les plantes bourgeonnent.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé : Réveil des insectes',
                '桃始華 – táo shǐ huá : Le pêcher commence à fleurir.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé : Réveil des insectes',
                '倉庚鳴 – cāng gēng míng : Le loriot chante.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé : Réveil des insectes',
                '鷹化為鳩 – yīng huà wéi jiū : L’aigle se métamorphose en tourterelle.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn : Équinoxe de printemps',
                '玄鳥至 – xuán niǎo zhì : Les hirondelles arrivent.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn : Équinoxe de printemps',
                '雷乃發聲 – léi nǎi fāshēng : 	Le tonnerre gronde.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn : Équinoxe de printemps',
                '始電 – shǐ diàn : Premiers éclairs.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng : Pure clarté',
                '桐始華 – tóng shǐ huá : L’abrasin commence à fleurir.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng : Pure clarté',
                '田鼠化為鴽 – tiánshǔ huà wéi rú : La taupe se métamorphose en caille.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng : Pure clarté',
                '虹始見 – hóng shǐ jiàn : Les arcs-en-ciel commencent à apparaître.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ : Pluie des céréales',
                '萍始生 – píng shǐ shēng : Les lentilles d’eau commencent à pousser.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ : Pluie des céréales',
                '鳴鳩拂其羽 – míng jiū fú qí yǔ : La tourterelle chante en déployant ses ailes.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ : Pluie des céréales',
                '戴勝降于桑 – dài shèng jiàng yú sāng : La huppe se pose sur le mûrier.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià : Établissement de l’été',
                '蝼蝈鸣 – lóu guō míng : Les grenouilles croassent.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià : Établissement de l’été',
                '蚯蚓出 – qiūyǐn chū : Les vers de terre sortent.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià : Établissement de l’été',
                '王瓜生 – wáng guā shēng : Les concombres commencent à pousser.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn : Épis à moitié pleins',
                '苦菜秀 – kǔ cài xiù : Les laiterons fleurissent.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn : Épis à moitié pleins',
                '靡草死 – mícǎo sǐ : Les délicates draves dépérissent.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn : Épis à moitié pleins',
                '小暑至 – xiǎoshǔ zhì : Les petites chaleurs arrivent.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng : Épis en barbe',
                '螳螂生 – tángláng shēng : La mante religieuse naît.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng : Épis en barbe',
                '鵙始鳴 – jú shǐ míng : La pie-grièche commence à chanter.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng : Épis en barbe',
                '反舌無声 – fǎnshé wúshēng : Le merle noir se tait.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì : Solstice d’été',
                '鹿角解 – lù jiǎo jiě : Le cerf perd ses bois.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì : Solstice d’été',
                '蜩始鳴 – tiáo shǐ míng : La cigale commence à striduler.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì : Solstice d’été',
                '半夏生 – bàn xià shēng : La Pinellia Ternata pousse.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ : Petite chaleur',
                '温風至 – wēn fēng zhì : Le vent tiède arrive.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ : Petite chaleur',
                '蟋蟀居壁 – xīshuài jū bì : Le grillon reste dans le mur.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ : Petite chaleur',
                '鷹乃学習 – yīng nǎi xuéxí : L’aigle apprend et s’exerce.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ : Grande chaleur',
                '腐草為萤 – fǔ cǎo wéi yíng : L’herbe pourrissante engendre les lucioles.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ : Grande chaleur',
                '土潤溽暑 – tǔ rùn rùshǔ : La terre est imbibée, l’air est chaud et humide.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ : Grande chaleur',
                '大雨時行 – dàyǔ shí xíng : Les grandes pluies commencent à tomber.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū : Établissement de l’automne',
                '涼風至 – liángfēng zhì : Le vent frais arrive.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū : Établissement de l’automne',
                '白露降 – báilù jiàng : La rosée blanche se dépose.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū : Établissement de l’automne',
                '寒蝉鳴 – hánchán míng : La cigale stridule.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ : Fin de la canicule',
                '鷹乃祭鳥 – yīng nǎi jì niǎo : L’aigle offre des oiseaux en sacrifice.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ : Fin de la canicule',
                '天地始肅 – tiāndì shǐ sù : Le Ciel et la Terre commencent à être rigoureux.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ : Fin de la canicule',
                '禾乃登 – hé nǎi dēng : Les céréales sont récoltées.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù : Rosée blanche',
                '鴻雁来 – hóngyàn lái : Les oies sauvages arrivent.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù : Rosée blanche',
                '玄鳥歸 – xuán niǎo guī : L’hirondelle revient.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù : Rosée blanche',
                '羣鳥養羞 – qún niǎo yǎng xiū : Tous les oiseaux engrangent des vivres.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn : Équinoxe d’automne',
                '雷乃收声 – léi nǎi shōu shēng : Le tonnerre cesse de gronder.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn : Équinoxe d’automne',
                '蟄虫坏戸 – zhé chóng huài hù : Les insectes hibernants retournent vers leur terrier.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn : Équinoxe d’automne',
                '水始涸 – shuǐ shǐ hé : L’eau commence à se tarir.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù : Rosée froide',
                '鴻雁来賓 – hóngyàn láibīn : Les oies sauvages arrivent et reçoivent l’hospitalité.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù : Rosée froide',
                '雀入大水為蛤 – què rù dà shuǐ wèi há : Le moineau plonge dans l’eau et se transforme en coquillage.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù : Rosée froide',
                '菊有黄華 – jú yǒu huáng huá : Le chrysanthème a des fleurs jaunes.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng : Arrivée du givre',
                '豺乃祭獸 – chái nǎi jì shòu : Le loup offre des bêtes en sacrifice.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng : Arrivée du givre',
                '草木黄落 – cǎomù huáng luò : Les feuilles jaunissent et tombent.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng : Arrivée du givre',
                '蟄虫咸俯 – zhé chóng xián fǔ : Les insectes hibernants se réfugient dans leur terrier.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng : Établissement de l’hiver',
                '水始冰 – shuǐ shǐ bīng : L’eau commence à geler.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng : Établissement de l’hiver',
                '地始凍 – dì shǐ dòng : La terre commence à geler.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng : Établissement de l’hiver',
                '野鶏入水為蜃 – yě jī rùshuǐ wèi shèn : Le faisan plonge dans l’eau et se transforme en huître.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě : Petite neige',
                '虹藏不見 – hóng cáng bùjiàn : L’arc-en-ciel se cache et disparaît.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě : Petite neige',
                '天氣上騰地氣下降 – tiān qì shàngténg dì qì xiàjiàng : Le souffle céleste monte, le souffle terrestre descend.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě : Petite neige',
                '閉塞而成冬 – bìsè ér chéng dōng : Tout est clos, l’hiver s’installe.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě : Grande neige',
                '鹖鴠不鳴 – hé dàn bù míng : Le faisan jaune ne chante plus.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě : Grande neige',
                '虎始交 – hǔ shǐ jiāo : Le tigre commence à s’accoupler.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě : Grande neige',
                '茘挺出 – lì tǐng chū : L’iris sort de terre.',
            ],
        ]
    ,
    en:
        [
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì: Winter Solstice',
                '蚯蚓結 – qiūyǐn jié: Earth-worms curl up.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì: Winter Solstice',
                '麋角解 – mí jiǎo jiě: Mi Deer shed their horns.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '癸 – guǐ',
                '冬至 – dōngzhì: Winter Solstice',
                '水泉動 – shuǐquán dòng: Springs of water are in movement.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán: Moderate Cold',
                '雁北鄉 – yàn běi xiāng: Wild geese go north.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán: Moderate Cold',
                '鵲始巢 – què shǐ cháo: Magpies begin to build nests.',
            ],
            [
                '太暘 – tài yáng',
                '丑 – chǒu',
                '癸 – guǐ',
                '小寒 – xiǎohán: Moderate Cold',
                '野鶏始雛 – yě jī shǐ chú: Pheasants begin to crow.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán: Severe Cold',
                '鶏始乳 – jī shǐ rǔ: Hens begin to hatch.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán: Severe Cold',
                '鷙鳥厲疾 – zhì niǎo lì jí: Birds of prey fly high and fast.',
            ],
            [
                '厥陰 – jué yīn',
                '丑 – chǒu',
                '癸 – guǐ',
                '大寒 – dàhán: Severe Cold',
                '水澤腹堅 – shuǐ zé fù jiān: Rivers and lakes are frozen thick.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn: Spring commences',
                '東風解凍 – dōngfēng jiědòng: East winds dissipate cold.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn: Spring commences',
                '蟄蟲始振 – zhéchóng shǐzhèn: Hibernating creatures begin to move.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '立春 – lìchūn: Spring commences',
                '魚上冰 – yú shàng bīng: Fish rise up to the ice.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ: Spring Showers',
                '獺祭魚 – tǎ jì yú: Otters sacrifice fish.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ: Spring Showers',
                '鴻雁來 – hóngyàn lái: Wild geese appear.',
            ],
            [
                '厥陰 – jué yīn',
                '寅 – yín',
                '甲 – jiǎ',
                '雨水 – yǔshuǐ: Spring Showers',
                '草木萌動 – cǎomù méngdòng: Plants bud and grow.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé: Insects Waken',
                '桃始華 – táo shǐ huá: Peach trees begin to blossom.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé: Insects Waken',
                '倉庚鳴 – cāng gēng míng: Orioles sing.',
            ],
            [
                '厥陰 – jué yīn',
                '卯 – mǎo',
                '甲 – jiǎ',
                '啓蟄 – jīngzhé: Insects Waken',
                '鷹化為鳩 – yīng huà wéi jiū: Hawks are transformed into doves.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn: Vernal Equinox',
                '玄鳥至 – xuán niǎo zhì: Swallows arrive.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn: Vernal Equinox',
                '雷乃發聲 – léi nǎi fāshēng: 	Thunder utters its voice.',
            ],
            [
                '少陰 – shǎo yīn',
                '卯 – mǎo',
                '乙 – yǐ',
                '春分 – chūnfēn: Vernal Equinox',
                '始電 – shǐ diàn: Lightning begins to be seen.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng: Bright and Clear',
                '桐始華 – tóng shǐ huá: Elaeococca begins to flower.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng: Bright and Clear',
                '田鼠化為鴽 – tiánshǔ huà wéi rú: Moles are transformed into quails.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '清明 – qīngmíng: Bright and Clear',
                '虹始見 – hóng shǐ jiàn: Rainbows begin to appear.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ: Cereal Rain',
                '萍始生 – píng shǐ shēng: Duckweed begins to grow.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ: Cereal Rain',
                '鳴鳩拂其羽 – míng jiū fú qí yǔ: Cooing doves clap their wings.',
            ],
            [
                '少陰 – shǎo yīn',
                '辰 – chén',
                '乙 – yǐ',
                '穀雨 – gǔyǔ : Cereal Rain',
                '戴勝降于桑 – dài shèng jiàng yú sāng : Crested birds light on mulberry trees.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià: Summer commences',
                '蝼蝈鸣 – lóu guō míng: Green frogs croak.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià: Summer commences',
                '蚯蚓出 – qiūyǐn chū: Earth-worms appear.',
            ],
            [
                '少陰 – shǎo yīn',
                '巳 – sì',
                '丙 – bǐng',
                '立夏 – lìxià: Summer commences',
                '王瓜生 – wáng guā shēng: Royal melons grow.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn: Cereal Ears form',
                '苦菜秀 – kǔ cài xiù: Sow-thistle is in seed.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn: Cereal Ears form',
                '靡草死 – mícǎo sǐ: Delicate herbs die.',
            ],
            [
                '少暘 – shǎo yáng',
                '巳 – sì',
                '丙 – bǐng',
                '小満 – xiǎomǎn: Cereal Ears form',
                '小暑至 – xiǎoshǔ zhì: Slight heat arrives.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng: Cereals on Ear',
                '螳螂生 – tángláng shēng: Praying mantis is born.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng: Cereals on Ear',
                '鵙始鳴 – jú shǐ míng: Shrikes begin to cry.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丙 – bǐng',
                '芒種 – mángzhòng: Cereals on Ear',
                '反舌無声 – fǎnshé wúshēng: Mockingbirds cease to sing.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì: Summer Solstice',
                '鹿角解 – lù jiǎo jiě: Deer shed their horns.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì: Summer Solstice',
                '蜩始鳴 – tiáo shǐ míng: Cicadas begin to sing.',
            ],
            [
                '少暘 – shǎo yáng',
                '午 – wǔ',
                '丁 – dīng',
                '夏至 – xiàzhì: Summer Solstice',
                '半夏生 – bàn xià shēng: Midsummer herb grows.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ: Moderate Heat',
                '温風至 – wēn fēng zhì: Warm winds come.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ: Moderate Heat',
                '蟋蟀居壁 – xīshuài jū bì: Crickets live in the walls.',
            ],
            [
                '少暘 – shǎo yáng',
                '未 – wèi',
                '丁 – dīng / 戊 – wù',
                '小暑 – xiǎoshǔ: Moderate Heat',
                '鷹乃学習 – yīng nǎi xuéxí: Young hawks learn to fly.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ: Great Heat',
                '腐草為萤 – fǔ cǎo wéi yíng: 	Decaying grass becomes fireflies.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ: Great Heat',
                '土潤溽暑 – tǔ rùn rùshǔ: Ground is humid and air is hot.',
            ],
            [
                '太陰 – tài yīn',
                '未 – wèi',
                '丁 – dīng / 己 – jǐ',
                '大暑 – dàshǔ: Great Heat',
                '大雨時行 – dàyǔ shí xíng: Great rains come frequently.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū: Fall commences',
                '涼風至 – liángfēng zhì: Cool winds arrive.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū: Fall commences',
                '白露降 – báilù jiàng: White dew descends.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '立秋 – lìqiū: Fall commences',
                '寒蝉鳴 – hánchán míng: Autumn cicadas chirp.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ: End of Heat',
                '鷹乃祭鳥 – yīng nǎi jì niǎo: Hawks sacrifice birds.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ: End of Heat',
                '天地始肅 – tiāndì shǐ sù: Heaven and Earth begin to be severe.',
            ],
            [
                '太陰 – tài yīn',
                '申 – shēn',
                '庚 – gēng',
                '処暑 – chǔshǔ: End of Heat',
                '禾乃登 – hé nǎi dēng: Grain is harvested.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù: White Dew',
                '鴻雁来 – hóngyàn lái: Wild geese arrive.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù: White Dew',
                '玄鳥歸 – xuán niǎo guī: Swallows return.',
            ],
            [
                '太陰 – tài yīn',
                '酉 – yǒu',
                '庚 – gēng',
                '白露 – báilù: White Dew',
                '羣鳥養羞 – qún niǎo yǎng xiū: All birds store up provisions.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn: Fall Equinox',
                '雷乃收声 – léi nǎi shōu shēng: Thunder restrains its voice.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn: Fall Equinox',
                '蟄虫坏戸 – zhé chóng huài hù: Hibernating creatures stop up entrances to their burrows.',
            ],
            [
                '暘明 – yáng míng',
                '酉 – yǒu',
                '辛 – xīn',
                '秋分 – qiūfēn: Fall Equinox',
                '水始涸 – shuǐ shǐ hé: Waters begin to dry up.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù: Cold Dew',
                '鴻雁来賓 – hóngyàn láibīn: Wild geese come as guests.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù: Cold Dew',
                '雀入大水為蛤 – què rù dà shuǐ wèi há: Sparrows enter the sea and become molluscs.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '寒露 – hánlù: Cold Dew',
                '菊有黄華 – jú yǒu huáng huá: Chrysanthemums show yellow flowers.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng: Frost',
                '豺乃祭獸 – chái nǎi jì shòu: Wolves sacrifice large animals.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng: Frost',
                '草木黄落 – cǎomù huáng luò: Leaves of plants become yellow and fall.',
            ],
            [
                '暘明 – yáng míng',
                '戌 – xū',
                '辛 – xīn',
                '霜降 – shuāngjiàng: Frost',
                '蟄虫咸俯 – zhé chóng xián fǔ: Hibernating creatures all push downward.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng: Winter commences',
                '水始冰 – shuǐ shǐ bīng: Water begins to freeze.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng: Winter commences',
                '地始凍 – dì shǐ dòng: Ground begins to harden.',
            ],
            [
                '暘明 – yáng míng',
                '亥 – hài',
                '壬 – rén',
                '立冬 – lìdōng: Winter commences',
                '野鶏入水為蜃 – yě jī rùshuǐ wèi shèn: Pheasants enter the water and become oysters.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě: Light Snow',
                '虹藏不見 – hóng cáng bùjiàn: Rainbows hide and are invisible.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě: Light Snow',
                '天氣上騰地氣下降 – tiān qì shàngténg dì qì xiàjiàng: Heaven’s ether ascends, Earth’s ether descends.',
            ],
            [
                '太暘 – tài yáng',
                '亥 – hài',
                '壬 – rén',
                '小雪 – xiǎoxuě: Light Snow',
                '閉塞而成冬 – bìsè ér chéng dōng: All is closed up and winter is fully formed.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě: Heavy Snow',
                '鹖鴠不鳴 – hé dàn bù míng: Yellow pheasants stop their cries.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě: Heavy Snow',
                '虎始交 – hǔ shǐ jiāo: Tigers begin to pair.',
            ],
            [
                '太暘 – tài yáng',
                '子 – zǐ',
                '壬 – rén',
                '大雪 – dàxuě: Heavy Snow',
                '茘挺出 – lì tǐng chū: Broom-sedge grows.',
            ],
        ]
};
