export const Periods = [
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
    [
        'Ligne 1',
        'Ligne 2',
        'Ligne 3',
        'Ligne 4',
        'Ligne 5',
    ],
];
