export type SymbolsMap = {
    gan: [string, string][];
    zhi: [string, string][];
    energies: [string, string][];
    polarities: [string, string][];
    signs: [string, string][];
    elementSigns: [string, string][];
    elements: string[];
    directions: string[];
    orientations: string[];
    symbols: string[];
};

type smap = {
    fr: SymbolsMap;
    en: SymbolsMap;
};

export const symbolsmap: smap = {
    fr: {
        gan: [
            ['甲', 'jiǎ'],
            ['乙', 'yǐ'],
            ['丙', 'bǐng'],
            ['丁', 'dīng'],
            ['戊', 'wù'],
            ['己', 'jǐ'],
            ['庚', 'gēng'],
            ['辛', 'xīn'],
            ['壬', 'rén'],
            ['癸', 'guǐ']
        ],
        zhi: [
            ['子', 'zǐ'],
            ['丑', 'chǒu'],
            ['寅', 'yín'],
            ['卯', 'mǎo'],
            ['辰', 'chén'],
            ['巳', 'sì'],
            ['午', 'wǔ'],
            ['未', 'wèi'],
            ['申', 'shēn'],
            ['酉', 'yǒu'],
            ['戌', 'xū'],
            ['亥', 'hài']
        ],
        energies: [
            ['少陰', 'shǎo yīn'],
            ['太陰', 'tài yīn'],
            ['少暘', 'shǎo yáng'],
            ['暘明', 'yáng míng'],
            ['太暘', 'tài yáng'],
            ['厥陰', 'jué yīn']
        ],
        polarities: [
            ['陽', 'yáng'],
            ['陰', 'yīn']
        ],
        signs: [
            ['鼠 Rat', 'shǔ'],
            ['牛 Bœuf', 'niú'],
            ['虎 Tigre', 'hǔ'],
            ['兔 Lapin', 'tù'],
            ['龍 Dragon', 'lóng'],
            ['蛇 Serpent', 'shé'],
            ['馬 Cheval', 'mǎ'],
            ['羊 Chèvre', 'yáng'],
            ['猴 Singe', 'hóu'],
            ['鷄 Coq', 'jī'],
            ['狗 Chien', 'gǒu'],
            ['猪 Cochon', 'zhū']
        ],
        elementSigns: [
            ['木 Bois', 'mù'],
            ['木 Bois', 'mù'],
            ['火 Feu', 'huǒ'],
            ['火 Feu', 'huǒ'],
            ['土 Terre', 'tǔ'],
            ['土 Terre', 'tǔ'],
            ['金 Métal', 'jīn'],
            ['金 Métal', 'jīn'],
            ['水 Eau', 'shuǐ'],
            ['水 Eau', 'shuǐ']
        ],
        elements: ['Terre', 'Métal', 'Eau', 'Bois', 'Feu'],
        directions: [
            'le Nord',
            'le Centre',
            'l’Est',
            'l’Est',
            'le Centre',
            'le Sud',
            'le Sud',
            'le Centre',
            'l’Ouest',
            'l’Ouest',
            'le Centre',
            'le Nord'
        ],
        orientations: [
            'Nord',
            'Nord-Nord-Est',
            'Est-Nord-Est',
            'Est',
            'Est-Sud-Est',
            'Sud-Sud-Est',
            'Sud',
            'Sud-Sud-Ouest',
            'Ouest-Sud-Ouest',
            'Ouest',
            'Ouest-Nord-Ouest',
            'Nord-Nord-Ouest'
        ],
        symbols: [
            'Métal au fond de la mer',
            'Métal au fond de la mer',
            'Feu dans le four',
            'Feu dans le four',
            'Bois de la grande forêt',
            'Bois de la grande forêt',
            'Terre au bord des routes',
            'Terre au bord des routes',
            "Métal de la pointe de l'épée",
            "Métal de la pointe de l'épée",
            'Feu au sommet des montagnes',
            'Feu au sommet des montagnes',
            'Eau de petite source',
            'Eau de petite source',
            'Terre sur les remparts',
            'Terre sur les remparts',
            'Métal du chandelier blanc',
            'Métal du chandelier blanc',
            'Bois du saule',
            'Bois du saule',
            'Eau de source',
            'Eau de source',
            'Terre sur le toit',
            'Terre sur le toit',
            'Feu du tonnerre',
            'Feu du tonnerre',
            'Bois du sapin centenaire',
            'Bois du sapin centenaire',
            'Eau du long fleuve',
            'Eau du long fleuve',
            'Métal dans le sable',
            'Métal dans le sable',
            'Feu au pied des montagnes',
            'Feu au pied des montagnes',
            'Bois des plaines',
            'Bois des plaines',
            'Terre sur les murs',
            'Terre sur les murs',
            "Métal blanc mélangé avec de l'or",
            "Métal blanc mélangé avec de l'or",
            'Feu du phare',
            'Feu du phare',
            'Eau du fleuve',
            'Eau du fleuve',
            "Terre d'une grande plaine",
            "Terre d'une grande plaine",
            'Métal des bijoux',
            'Métal des bijoux',
            'Bois du mûrier',
            'Bois du mûrier',
            'Eau de grande source',
            'Eau de grande source',
            'Terre dans le sable',
            'Terre dans le sable',
            'Feu dans le ciel',
            'Feu dans le ciel',
            'Bois du grenadier',
            'Bois du grenadier',
            'Eau du grand océan',
            'Eau du grand océan'
        ]
    },

    //@todo: translate here
    en: {
        gan: [
            ['甲', 'jiǎ'],
            ['乙', 'yǐ'],
            ['丙', 'bǐng'],
            ['丁', 'dīng'],
            ['戊', 'wù'],
            ['己', 'jǐ'],
            ['庚', 'gēng'],
            ['辛', 'xīn'],
            ['壬', 'rén'],
            ['癸', 'guǐ']
        ],
        zhi: [
            ['子', 'zǐ'],
            ['丑', 'chǒu'],
            ['寅', 'yín'],
            ['卯', 'mǎo'],
            ['辰', 'chén'],
            ['巳', 'sì'],
            ['午', 'wǔ'],
            ['未', 'wèi'],
            ['申', 'shēn'],
            ['酉', 'yǒu'],
            ['戌', 'xū'],
            ['亥', 'hài']
        ],
        energies: [
            ['少陰', 'shǎo yīn'],
            ['太陰', 'tài yīn'],
            ['少暘', 'shǎo yáng'],
            ['暘明', 'yáng míng'],
            ['太暘', 'tài yáng'],
            ['厥陰', 'jué yīn']
        ],
        polarities: [
            ['陽', 'yáng'],
            ['陰', 'yīn']
        ],
        signs: [
            ['鼠 Rat', 'shǔ'],
            ['牛 Bœuf', 'niú'],
            ['虎 Tigre', 'hǔ'],
            ['兔 Lapin', 'tù'],
            ['龍 Dragon', 'lóng'],
            ['蛇 Serpent', 'shé'],
            ['馬 Cheval', 'mǎ'],
            ['羊 Chèvre', 'yáng'],
            ['猴 Singe', 'hóu'],
            ['鷄 Coq', 'jī'],
            ['狗 Chien', 'gǒu'],
            ['猪 Cochon', 'zhū']
        ],
        elementSigns: [
            ['木 Bois', 'mù'],
            ['木 Bois', 'mù'],
            ['火 Feu', 'huǒ'],
            ['火 Feu', 'huǒ'],
            ['土 Terre', 'tǔ'],
            ['土 Terre', 'tǔ'],
            ['金 Métal', 'jīn'],
            ['金 Métal', 'jīn'],
            ['水 Eau', 'shuǐ'],
            ['水 Eau', 'shuǐ']
        ],
        elements: ['Terre', 'Métal', 'Eau', 'Bois', 'Feu'],
        directions: [
            'le Nord',
            'le Centre',
            'l’Est',
            'l’Est',
            'le Centre',
            'le Sud',
            'le Sud',
            'le Centre',
            'l’Ouest',
            'l’Ouest',
            'le Centre',
            'le Nord'
        ],
        orientations: [
            'Nord',
            'Nord-Nord-Est',
            'Est-Nord-Est',
            'Est',
            'Est-Sud-Est',
            'Sud-Sud-Est',
            'Sud',
            'Sud-Sud-Ouest',
            'Ouest-Sud-Ouest',
            'Ouest',
            'Ouest-Nord-Ouest',
            'Nord-Nord-Ouest'
        ],
        symbols: [
            'Métal au fond de la mer',
            'Métal au fond de la mer',
            'Feu dans le four',
            'Feu dans le four',
            'Bois de la grande forêt',
            'Bois de la grande forêt',
            'Terre au bord des routes',
            'Terre au bord des routes',
            "Métal de la pointe de l'épée",
            "Métal de la pointe de l'épée",
            'Feu au sommet des montagnes',
            'Feu au sommet des montagnes',
            'Eau de petite source',
            'Eau de petite source',
            'Terre sur les remparts',
            'Terre sur les remparts',
            'Métal du chandelier blanc',
            'Métal du chandelier blanc',
            'Bois du saule',
            'Bois du saule',
            'Eau de source',
            'Eau de source',
            'Terre sur le toit',
            'Terre sur le toit',
            'Feu du tonnerre',
            'Feu du tonnerre',
            'Bois du sapin centenaire',
            'Bois du sapin centenaire',
            'Eau du long fleuve',
            'Eau du long fleuve',
            'Métal dans le sable',
            'Métal dans le sable',
            'Feu au pied des montagnes',
            'Feu au pied des montagnes',
            'Bois des plaines',
            'Bois des plaines',
            'Terre sur les murs',
            'Terre sur les murs',
            "Métal blanc mélangé avec de l'or",
            "Métal blanc mélangé avec de l'or",
            'Feu du phare',
            'Feu du phare',
            'Eau du fleuve',
            'Eau du fleuve',
            "Terre d'une grande plaine",
            "Terre d'une grande plaine",
            'Métal des bijoux',
            'Métal des bijoux',
            'Bois du mûrier',
            'Bois du mûrier',
            'Eau de grande source',
            'Eau de grande source',
            'Terre dans le sable',
            'Terre dans le sable',
            'Feu dans le ciel',
            'Feu dans le ciel',
            'Bois du grenadier',
            'Bois du grenadier',
            'Eau du grand océan',
            'Eau du grand océan'
        ]
    }
};
